# Generated by Django 5.0.7 on 2024-08-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DispositionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Designation', models.CharField(blank=True, max_length=255, null=True)),
                ('BPS', models.CharField(blank=True, max_length=255, null=True)),
                ('ZONE', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_of_Birth', models.CharField(blank=True, max_length=255, null=True)),
                ('CNIC_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_of_Entry_into_Govt_Service', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_of_Promotion', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_of_Retirement', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_of_Posting_in_rto_ii_Karachi', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_of_Posting_in_Zone', models.CharField(blank=True, max_length=255, null=True)),
                ('Personal_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Cell_No', models.CharField(blank=True, max_length=255, null=True)),
                ('Education', models.CharField(blank=True, max_length=255, null=True)),
                ('Domicile', models.CharField(blank=True, max_length=255, null=True)),
                ('Residential_Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Basic_Pay', models.CharField(blank=True, max_length=255, null=True)),
                ('Personal_Pay', models.CharField(blank=True, max_length=255, null=True)),
                ('Total', models.CharField(blank=True, max_length=255, null=True)),
                ('Email_Address', models.CharField(blank=True, max_length=255, null=True)),
                ('Remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
