# Generated by Django 5.0.7 on 2024-09-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositionlist',
            name='mode_of_appointment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
