# Generated by Django 5.0.7 on 2024-08-10 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic_no', models.CharField(max_length=20)),
                ('personnel_number', models.CharField(blank=True, max_length=20)),
                ('old_unit', models.CharField(blank=True, max_length=255)),
                ('new_unit', models.CharField(blank=True, max_length=255)),
                ('transfer_date', models.DateField()),
                ('reason_for_transfer', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('zone', models.CharField(max_length=255)),
                ('order_approved_by', models.CharField(max_length=255)),
                ('transfer_document', models.FileField(blank=True, null=True, upload_to='transfer_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.dispositionlist')),
            ],
        ),
    ]
