# Generated by Django 5.0.7 on 2025-01-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_inventorystock_dispositionlist_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_no', models.CharField(max_length=50, unique=True)),
                ('current_designation', models.CharField(max_length=100)),
                ('new_designation', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField()),
                ('order_docx', models.FileField(blank=True, null=True, upload_to='promotion_orders/')),
                ('status', models.IntegerField(default=1)),
                ('zone_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
