# Generated by Django 5.0.7 on 2025-01-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_dispositionlist_mode_of_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositionlist',
            name='mode_of_appointment',
        ),
        migrations.AddField(
            model_name='dispositionlist',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
