# Generated by Django 5.0.7 on 2024-08-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_transferposting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferposting',
            name='cnic_no',
        ),
        migrations.RemoveField(
            model_name='transferposting',
            name='personnel_number',
        ),
    ]
