# Generated by Django 5.0.7 on 2025-01-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='updated_at',
        ),
    ]
