# Generated by Django 5.0.7 on 2024-08-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_rename_order_approved_by_transferposting_chief_order_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferposting',
            name='chief_transfer_date',
            field=models.DateField(blank=True),
        ),
    ]
