# Generated by Django 5.0.7 on 2025-01-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_remove_dispositionlist_mode_of_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferposting',
            name='chief_order_number',
            field=models.CharField(max_length=255),
        ),
    ]
