# Generated by Django 5.0.7 on 2024-08-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_alter_transferposting_chief_transfer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferposting',
            name='chief_transfer_date',
            field=models.DateField(null=True),
        ),
    ]
