# Generated by Django 5.0.7 on 2024-08-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_remove_transferposting_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferposting',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
