# Generated by Django 5.0.7 on 2025-01-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_remove_promotion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='order_number',
            field=models.CharField(max_length=50),
        ),
    ]
