# Generated by Django 5.0.7 on 2024-08-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_transferposting_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferposting',
            name='transfer_document',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='transfer_documents/'),
        ),
    ]
