# Generated by Django 5.0.7 on 2025-02-03 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_alter_promotion_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_deducted', models.PositiveIntegerField()),
                ('officerName', models.CharField(default=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.inventorystock')),
            ],
        ),
    ]
