# Generated by Django 5.0.7 on 2024-08-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_alter_transferposting_chief_transfer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferposting',
            name='zone_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
