# Generated by Django 5.0.7 on 2025-02-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_outgoingstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystock',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
