# Generated by Django 5.0.7 on 2024-08-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_alter_transferposting_old_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferposting',
            name='new_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
