# Generated by Django 5.0.7 on 2024-08-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_leaveapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='employee_cnic',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='employee_name',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='days_granted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_document',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/'),
        ),
    ]
