# Generated by Django 5.0.7 on 2025-02-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_inventorystock_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingstock',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='stationaryLetter/'),
        ),
    ]
