# Generated by Django 5.0.7 on 2024-08-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_remove_leaveapplication_employee_cnic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositionlist',
            name='additional_charge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dispositionlist',
            name='additional_charge_lro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
