# Generated by Django 5.0.7 on 2025-02-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_outgoingstock_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingstock',
            name='document',
        ),
        migrations.AddField(
            model_name='outgoingstock',
            name='order_docx',
            field=models.FileField(blank=True, null=True, upload_to='stationary_letters/'),
        ),
    ]
