# Generated by Django 5.0.7 on 2024-08-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_alter_transferposting_new_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferposting',
            name='zone_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
