# Generated by Django 5.0.7 on 2024-08-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_alter_transferposting_zone_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='zone_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
