# Generated by Django 5.0.7 on 2025-02-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_remove_outgoingstock_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingstock',
            name='letter_date',
            field=models.DateField(null=True),
        ),
    ]
