# Generated by Django 5.0.7 on 2025-02-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_outgoingstock_letter_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(default=True, max_length=255)),
                ('OfficerName', models.CharField(default=True, max_length=255)),
                ('Designation', models.CharField(default=True, max_length=255)),
                ('Zone', models.CharField(default=True, max_length=255)),
                ('serial_No', models.CharField(default=True, max_length=255)),
                ('Remarks', models.CharField(default=True, max_length=255)),
                ('Source', models.CharField(default=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
