# Generated by Django 5.0.7 on 2025-02-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_oldstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldstock',
            name='date',
        ),
    ]
