# Generated by Django 5.0.7 on 2025-02-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_remove_oldstock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingstock',
            name='serial_No',
            field=models.DateField(null=True),
        ),
    ]
