# Generated by Django 5.0.7 on 2024-09-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanation',
            name='zone_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
