# Generated by Django 5.0.7 on 2025-03-28 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0013_outgoingstock_serial_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=255)),
                ('decease_type', models.CharField(max_length=255)),
                ('application_date', models.DateField()),
                ('bill_document', models.FileField(upload_to='medical_bills/')),
                ('medical_bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hospital_name', models.CharField(max_length=255)),
                ('treatment_start_date', models.DateField()),
                ('treatment_end_date', models.DateField()),
                ('diagnosis_details', models.TextField()),
                ('bill_status', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_relationship', models.CharField(max_length=255)),
                ('patient_gender', models.CharField(max_length=50)),
                ('surgeon_name', models.CharField(max_length=255)),
                ('hospital_contact', models.CharField(max_length=255)),
                ('claim_ref_number', models.CharField(max_length=255)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=50)),
                ('date_of_claim_received', models.DateField()),
                ('approved_bill_docx', models.FileField(upload_to='approved_bills/')),
                ('authorized_person', models.CharField(max_length=255)),
                ('date_of_submission', models.DateField()),
                ('authorized_docx', models.FileField(upload_to='authorized_docs/')),
                ('sanction_bill', models.FileField(upload_to='sanction_bills/')),
                ('bill_submission_date', models.DateField()),
                ('bill_order_docx', models.FileField(upload_to='bill_orders/')),
                ('date_of_approval_agpr', models.DateField()),
                ('approved_sanction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.dispositionlist')),
            ],
        ),
    ]
