# Generated by Django 5.0.7 on 2024-09-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0013_explanation_zone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Earned Leave', 'Earned Leave'), ('Ex-Pakistan Leave', 'Ex-Pakistan Leave'), ('Medical Leave', 'Medical Leave'), ('Study Leave', 'Study Leave'), ('Special Leave', 'Special Leave'), ('Maternity Leave', 'Maternity Leave')], max_length=50),
        ),
    ]
