# Generated by Django 5.0.7 on 2025-03-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0014_medicalbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalbill',
            name='Bank_Address',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicalbill',
            name='BranchCode',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicalbill',
            name='IBAN',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicalbill',
            name='bank_name',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicalbill',
            name='bill_ref_number',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicalbill',
            name='payment_status',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicalbill',
            name='remarks',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalbill',
            name='authorized_person',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalbill',
            name='bill_status',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalbill',
            name='bill_type',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalbill',
            name='claim_ref_number',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalbill',
            name='decease_type',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalbill',
            name='hospital_contact',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalbill',
            name='hospital_name',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalbill',
            name='patient_gender',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalbill',
            name='patient_name',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalbill',
            name='patient_relationship',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalbill',
            name='surgeon_name',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
