# Generated by Django 5.0.7 on 2024-09-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0014_alter_leaveapplication_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositionlist',
            name='emp_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispositionlist',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
