# Generated by Django 5.0.7 on 2024-09-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0015_dispositionlist_emp_age_dispositionlist_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositionlist',
            name='emp_age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
