# Generated by Django 5.0.7 on 2025-09-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0015_medicalbill_bank_address_medicalbill_branchcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('assigned', 'Assigned'), ('repair', 'In Repair'), ('retired', 'Retired')], default='in_stock', max_length=20)),
                ('Personnel', models.CharField(default=True, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
