# Generated by Django 5.0.7 on 2025-01-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0016_alter_dispositionlist_emp_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, unique=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
