# Generated by Django 5.0.7 on 2025-09-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0016_pc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='Personnel',
        ),
        migrations.AddField(
            model_name='pc',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pcs', to='WebApp.dispositionlist'),
        ),
    ]
