# Generated by Django 5.0.7 on 2025-09-19 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0017_remove_pc_personnel_pc_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
