# Generated by Django 5.0.7 on 2025-02-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0018_outgoingstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingstock',
            name='officerName',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
