# Generated by Django 5.0.7 on 2025-09-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0018_alter_pc_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='created_date',
        ),
    ]
