# Generated by Django 5.0.7 on 2025-09-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0019_remove_pc_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
